# Required NTFS Structures and Field Definitions

| # | Structure / Field                | Definition                                                                                                                                                                                                   | Forensic Value                                                                                                                                                |
| - | -------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1 | **Boot Sector**                  | The first sector of an NTFS volume. It contains information needed to identify and interpret the file system, including bytes per sector, sectors per cluster, the location of the MFT, and the MFT record size. | Helps determine how the NTFS volume is organized and where important metadata structures are located.                                                         |
| 2 | **MFT (Master File Table)**      | The central NTFS metadata structure. Each file and directory on an NTFS volume has an MFT record containing information about that object.                                                                   | Can provide filenames, timestamps, file attributes, relationships, and locations of file data.                                                                |
| 3 | **$STANDARD_INFORMATION**        | An MFT attribute containing standard metadata associated with a file or directory. It includes timestamps and file attributes.                                                                               | Provides important timeline information, including creation, modification, and access-related timestamps.                                                     |
| 4 | **$DATA**                        | The MFT attribute that represents the contents of a file. Depending on how the file is stored, the data may be resident inside the MFT record or stored in clusters elsewhere on the volume.                 | Allows investigators to locate and recover the actual contents of files.                                                                                      |
| 5 | **Alternate Data Streams (ADS)** | Additional named data streams associated with an NTFS file. A file can contain a primary data stream and one or more alternate streams.                                                               | ADS can contain information not immediately visible through normal file browsing and may include metadata or other potentially relevant data.         |
| 6 | **Clusters**                     | The basic allocation units used by NTFS to store file data. A cluster consists of one or more sectors.                                                                                                       | Understanding cluster allocation helps investigators determine where file data is stored and identify unused areas that may contain remnants of deleted data. |
| 7 | **Slack Space**                  | Unused space within an allocated cluster, typically occurring when a file does not completely fill its final cluster.                                                                                        | Slack space can contain remnants of previously stored information and may provide additional forensic evidence.                                               |
| 8 | **Data Runs**                    | Data-run information describes which clusters contain a file's non-resident data. NTFS uses compressed run information to map logical file data to cluster locations.                                        | Investigators can use data runs to locate and reconstruct non-resident file contents directly from a forensic disk image.                                     |
